apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ot-hospital-otfe-content
spec:
  microFrontend: ot-hospital-otfe
  element: ot-hospital-app
  attributes:
    - name: base-path
      value: /ot-hospital/
    - name: api-base
      value: /ot-api
    - name: hospital-id
      value: hospital-ba
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?ot-hospital(/.*)?$"
