apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
  - pairs:
      app.kubernetes.io/part-of: wac-hospital
      app.kubernetes.io/name: ot-hospital
    includeSelectors: true
    includeTemplates: true

resources:
  - ../../../apps/ot-hospital-otfe
  - ../../../apps/ot-hospital-api

components:
  - ../../../components/version-release
