apiVersion: apps/v1
kind: Deployment
metadata:
  name: ot-hospital-api
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /ot-openapi
            - name: BASE_URL
              value: /ot-openapi-ui
